=begin
#Flagr

#Flagr is a feature flagging, A/B testing and dynamic configuration microservice

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Flagr::ConstraintApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ConstraintApi' do
  before do
    # run before each test
    @instance = Flagr::ConstraintApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConstraintApi' do
    it 'should create an instance of ConstraintApi' do
      expect(@instance).to be_instance_of(Flagr::ConstraintApi)
    end
  end

  # unit tests for create_constraint
  # 
  # 
  # @param flag_id numeric ID of the flag
  # @param segment_id numeric ID of the segment
  # @param body create a constraint
  # @param [Hash] opts the optional parameters
  # @return [Constraint]
  describe 'create_constraint test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_constraint
  # 
  # 
  # @param flag_id numeric ID of the flag
  # @param segment_id numeric ID of the segment
  # @param constraint_id numeric ID of the constraint
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_constraint test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_constraints
  # 
  # 
  # @param flag_id numeric ID of the flag
  # @param segment_id numeric ID of the segment
  # @param [Hash] opts the optional parameters
  # @return [Array<Constraint>]
  describe 'find_constraints test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_constraint
  # 
  # 
  # @param flag_id numeric ID of the flag
  # @param segment_id numeric ID of the segment
  # @param constraint_id numeric ID of the constraint
  # @param body create a constraint
  # @param [Hash] opts the optional parameters
  # @return [Constraint]
  describe 'put_constraint test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
