=begin
#Flagr

#Flagr is a feature flagging, A/B testing and dynamic configuration microservice

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Flagr::SegmentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SegmentApi' do
  before do
    # run before each test
    @instance = Flagr::SegmentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SegmentApi' do
    it 'should create an instance of SegmentApi' do
      expect(@instance).to be_instance_of(Flagr::SegmentApi)
    end
  end

  # unit tests for create_segment
  # 
  # 
  # @param flag_id numeric ID of the flag to get
  # @param body create a segment under a flag
  # @param [Hash] opts the optional parameters
  # @return [Segment]
  describe 'create_segment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_segment
  # 
  # 
  # @param flag_id numeric ID of the flag
  # @param segment_id numeric ID of the segment
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_segment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_segments
  # 
  # 
  # @param flag_id numeric ID of the flag to get
  # @param [Hash] opts the optional parameters
  # @return [Array<Segment>]
  describe 'find_segments test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_segment
  # 
  # 
  # @param flag_id numeric ID of the flag
  # @param segment_id numeric ID of the segment
  # @param body update a segment
  # @param [Hash] opts the optional parameters
  # @return [Segment]
  describe 'put_segment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
