=begin
#Flagr

#Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 

OpenAPI spec version: 1.1.10

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for Flagr::TagApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TagApi' do
  before do
    # run before each test
    @instance = Flagr::TagApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TagApi' do
    it 'should create an instance of TagApi' do
      expect(@instance).to be_instance_of(Flagr::TagApi)
    end
  end

  # unit tests for create_tag
  # @param flag_id numeric ID of the flag
  # @param body create a tag
  # @param [Hash] opts the optional parameters
  # @return [Tag]
  describe 'create_tag test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_tag
  # @param flag_id numeric ID of the flag
  # @param tag_id numeric ID of the tag
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_tag test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_all_tags
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit the numbers of tags to return
  # @option opts [Integer] :offset return tags given the offset, it should usually set together with limit
  # @option opts [String] :value_like return tags partially matching given value
  # @return [Array<Tag>]
  describe 'find_all_tags test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_tags
  # @param flag_id numeric ID of the flag
  # @param [Hash] opts the optional parameters
  # @return [Array<Tag>]
  describe 'find_tags test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
