=begin
#Flagr

#Flagr is a feature flagging, A/B testing and dynamic configuration microservice

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Flagr::VariantApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VariantApi' do
  before do
    # run before each test
    @instance = Flagr::VariantApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VariantApi' do
    it 'should create an instance of VariantApi' do
      expect(@instance).to be_instance_of(Flagr::VariantApi)
    end
  end

  # unit tests for create_variant
  # 
  # 
  # @param flag_id numeric ID of the flag
  # @param body create a variant
  # @param [Hash] opts the optional parameters
  # @return [Variant]
  describe 'create_variant test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_variant
  # 
  # 
  # @param flag_id numeric ID of the flag
  # @param variant_id numeric ID of the variant
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_variant test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_variants
  # 
  # 
  # @param flag_id numeric ID of the flag
  # @param [Hash] opts the optional parameters
  # @return [Array<Variant>]
  describe 'find_variants test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_variant
  # 
  # 
  # @param flag_id numeric ID of the flag
  # @param variant_id numeric ID of the variant
  # @param body update a variant
  # @param [Hash] opts the optional parameters
  # @return [Variant]
  describe 'put_variant test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
